# Generated by Django 5.0.6 on 2024-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(default='Не в работе', max_length=20),
        ),
    ]
