# Generated by Django 5.0.6 on 2024-06-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clients_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='FIO_representative',
            field=models.CharField(default='', max_length=100),
        ),
    ]
