# Generated by Django 5.0.6 on 2024-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clients_fio_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='FIO_representative',
            field=models.CharField(max_length=100),
        ),
    ]
