# Generated by Django 5.0.6 on 2024-06-18 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
