# Generated by Django 5.0.6 on 2024-06-18 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_users_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(1999, 1, 1, 1, 1, 1)),
        ),
    ]
