# Generated by Django 5.0.6 on 2024-06-18 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_users_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 15, 7, 7, 338667)),
        ),
    ]
