# Generated by Django 5.0.6 on 2024-06-18 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_users_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
