# Generated by Django 5.0.6 on 2024-06-18 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_users_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='exp_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
